import React from 'react'
import './globals.css'
import type { Metadata } from 'next'

import TamaGuiProvider from '../providers/TamaGuiProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <TamaGuiProvider>{children}</TamaGuiProvider>
      </body>
    </html>
  )
}
